import "./globals.css";
import Nav from "../ui/nav";
import SupabaseProvider from "../utils/browserClient";
import { store } from "../store";
import { fetchInitialSnips } from "../store/snipsSlice";
import supabase from "../lib/supabase";
import Preloader from "./Preloader";
import { SnipWithComments as Snip } from "../lib/database";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  async function getSnips() {
    const { data, error } = await supabase
      .from("snips")
      .select(`* , comments (*)`)
      .order("id", { ascending: false });
    return { data, error };
  }
  const { data } = await getSnips();
  
  store.dispatch(fetchInitialSnips(data ?? []));

  return (
    <html lang="en">
      <body>
        <SupabaseProvider>
          <Preloader snips={data ?? []} />
          <div className="max-w-xl mx-auto">
            <Nav />
            {children}
          </div>
        </SupabaseProvider>
      </body>
    </html>
  );
}
