import "./globals.css";
import Nav from "../ui/nav";
import SupabaseProvider from "../lib/supabase-browser";
import { store } from "../store";
import { fetchInitialSnips } from "../store/snipsSlice";
import serverClient from "../lib/supabase-server";
import Preloader from "./Preloader";
import SessionProvider from "./SesssionProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const supabase = serverClient();
  async function getSnips() {
    const { data, error } = await supabase
      .from("snips")
      .select(`* , comments (*)`)
      .order("id", { ascending: false });
    return { data, error };
  }
  const { data } = await getSnips();

  store.dispatch(fetchInitialSnips(data ?? []));

  return (
    <html lang="en">
      <body>
        <SupabaseProvider>
          <Preloader snips={data ?? []} />
          <SessionProvider>
            <div className="max-w-xl mx-auto">
              <Nav />
              {children}
            </div>
          </SessionProvider>
        </SupabaseProvider>
      </body>
    </html>
  );
}
